### ISSUE TITLE
Why was the Display implementation for Object removed?

### ISSUE THREAD

**Issue by IovoslavIovchev** [jasonwilliams/boa#170]
Hello,

While playing around with this project I came accross:
```rust
#[test]
fn concat() {
    //TODO: array display formatter
```
and, after some digging, I found that at some point in the past `Display` _was_ implemented for `ValueData::Object` (as far as I know, arrays in `boa` are objects).

So why exactly was it removed? Was it because the previous implementation was too verbose?

**Comment by jasonwilliams** [comment]
Hey @IovoslavIovchev I can answer this one.
Basically we were experiencing stack overflows when printing objects.

After investigation I saw that the printer prints every property and slot for an object.
This creates an infinite loop because the prototype hidden slot of String will point to Object so all of Objects properties get printed and so on.

I think for now I changed object to just print {} (I tried reducing it to just properties but I can’t remember why that didn’t work)

Anyway, there is some work to be done need to match whatever the other implementations do

**Comment by jasonwilliams** [comment]
The output was getting too big and verbose. If there is a nice way to pretty print objects I’m for it.

**Comment by jasonwilliams** [comment]
If you wish to experiment you can try adding it back, then try printing a string object

**Comment by IovoslavIovchev** [comment]
I tried various forms of `String`s, `Object`s and `Array`s but none of them caused a stack overflow (I'm using 2427b3b, by the way).

Did a stack overflow occur every time, or just in particular cases?

**Comment by IovoslavIovchev** [comment]
One way to avoid verbosity (and a stack overflow) would be to only print own properties and not print the prototype, if that is something that might be deemed acceptable.

Additionally, pretty printing can be achieved by simply printing each new property on a new line.

**Comment by jasonwilliams** [comment]
Sure, it’s a good start

I think all objects should attempt to call their own .toString() counterpart before being displayed anyway.

**Comment by IovoslavIovchev** [comment]
I will take a look at re-implementing `Display` then.

**Comment by jasonwilliams** [comment]
Thanks @IovoslavIovchev

**Comment by IovoslavIovchev** [comment]
Done in #211
