### ISSUE TITLE
catch statement causes syntax error

### ISSUE THREAD

**Issue by gadget114514** [jasonwilliams/boa#375]
```javascript
try {
        var x = 1;
}
catch (e) { }
```
```
ParsingError: Expected token '(', got 'catch' in catch in try statement at line 4, col 1
```

**Comment by Razican** [comment]
Good "catch"!
The issue is in [`boa/src/syntax/parser/statement/try_stm/mod.rs#L67`](https://github.com/jasonwilliams/boa/blob/master/boa/src/syntax/parser/statement/try_stm/mod.rs#L67). We `peek()` the next token, and check if it's the `catch` keyword, but then, we don't consume it.

We should divide this parser into `TryStatement`, `Catch`, `Finally` and `CatchParameter`, as we can see in the [spec](https://tc39.es/ecma262/#sec-try-statement). Then, decide if we should parse `Catch` or `Finally` depending on the `peek()`. Those parsers should then `expect()` the `catch/finally` keywords.

**Comment by abhijeetbhagat** [comment]
I can take this up if no one else is working.

**Comment by HalidOdat** [comment]
Sure! Tell us if you need any help :+1:
