### ISSUE TITLE
Use a single Undefined value and point to that instead of multiple copies

### ISSUE THREAD

**Issue by jasonwilliams** [jasonwilliams/boa#54]
We generate ` Gc::new(ValueData::Undefined)` everywhere. 
https://github.com/jasonwilliams/boa/blob/master/src/lib/exec.rs#L109
https://github.com/jasonwilliams/boa/blob/master/src/lib/exec.rs#L131
https://github.com/jasonwilliams/boa/blob/master/src/lib/exec.rs#L322

It would be good to generate 1 undefined Value and reference this, it would live throughout the lifetime of the whole program, so could it be a static value?

**Comment by Razican** [comment]
That value would be a pointer-width value, why would it be good to reference it from multiple places? It would add one extra memory indirection, and slow down things, right?

**Comment by zgotsch** [comment]
Maybe I don't understand something, but making a single value seems like it would be the same amount of indirection as the current approach. One level of indirection could then be removed because it would no longer need to be `Gc` and `GcCell` since it should live for the entire lifetime of the program (though this would have to use some sort of abstraction over pointer types, which I don't really understand yet). This seems like a very small win to me though, so it seems low pri?

**Comment by jasonwilliams** [comment]
I agree, closing this ticket
